bigswitch/bosi

bosi/lib/environment.py
bosi/lib/helper.py
bosi/lib/node.py
etc/bosi_config/config.yaml
etc/t5/puppet_template/centos_compute.pp
etc/t5/puppet_template/centos_controller.pp
etc/t5/puppet_template/redhat_compute.pp
etc/t5/puppet_template/redhat_controller.pp
etc/t5/puppet_template/ubuntu_compute.pp
etc/t5/puppet_template/ubuntu_controller.pp
etc/t6/puppet_template/centos_compute.pp
etc/t6/puppet_template/centos_controller.pp
etc/t6/puppet_template/ubuntu_compute.pp
etc/t6/puppet_template/ubuntu_controller.pp

BVS-4446, add capability to change mtu

---

etc/t5/puppet_template/centos_compute.pp
etc/t5/puppet_template/centos_controller.pp
etc/t5/puppet_template/redhat_compute.pp
etc/t5/puppet_template/redhat_controller.pp
etc/t5/puppet_template/ubuntu_compute.pp
etc/t5/puppet_template/ubuntu_controller.pp
etc/t6/puppet_template/centos_compute.pp
etc/t6/puppet_template/centos_controller.pp

fix selinux

---

bosi/lib/helper.py

fix condition for ceph

---

etc/t5/bash_template/ubuntu_14.sh
etc/t6/bash_template/ubuntu_14.sh

don't restart apache2 on openstack controller

---

bosi/lib/helper.py

change mode from 777 to 644

---

bosi/lib/rest.py

suppress warning message

---

bosi/bosi.py
bosi/lib/helper.py
bosi/lib/node.py
etc/t5/puppet_template/centos_controller.pp
etc/t5/puppet_template/redhat_controller.pp
etc/t5/puppet_template/ubuntu_controller.pp
etc/t6/puppet_template/centos_controller.pp
etc/t6/puppet_template/ubuntu_controller.pp

add configuration for keystone client in restproxy

---

bosi/lib/helper.py

remove api version from auth_uri

---

etc/t5/puppet_template/centos_compute.pp
etc/t5/puppet_template/centos_controller.pp
etc/t5/puppet_template/redhat_controller.pp
etc/t5/puppet_template/ubuntu_compute.pp
etc/t5/puppet_template/ubuntu_controller.pp
etc/t6/puppet_template/centos_compute.pp
etc/t6/puppet_template/centos_controller.pp
etc/t6/puppet_template/ubuntu_compute.pp
etc/t6/puppet_template/ubuntu_controller.pp

evenly distribute dhcp namespaces to all dhcp agents

---

bosi/bosi.py

cleanup index.html

---

bosi/lib/helper.py

add support for sr-iov

---

etc/t5/bash_template/ubuntu_14.sh
etc/t6/bash_template/ubuntu_14.sh

restart apache2 instead of keystone

---

bosi/lib/rest.py

fix rest call to bcf controller

---

bosi/lib/constants.py
bosi/lib/helper.py
etc/t6/bash_template/ubuntu_14.sh
etc/t6/puppet_template/ubuntu_mongo.pp

BVS-4993, support mongodb

---

etc/bosi_config/config.yaml

change default openstack release to kilo

---

etc/bosi_config/config.yaml
etc/t5/puppet_template/centos_compute.pp
etc/t5/puppet_template/centos_controller.pp

don't reconfigure node gw in t5

---

bosi/lib/helper.py
etc/t6/python_template/admin_tabs.py
etc/t6/python_template/project_tabs.py

BVS-5034, hind router rule grid for kilo t6 deployment

---

bosi/lib/constants.py
bosi/lib/rest.py

refactor rest client

---

bosi/lib/constants.py

fix bsnstacklib version number for juno

---

etc/t5/bash_template/centos_7.sh
etc/t6/bash_template/centos_7.sh

BVS-4334, use selinux puppet module 0.2.5

---

etc/t5/puppet_template/ubuntu_compute.pp
etc/t5/selinux_template/centos.te
etc/t6/puppet_template/ubuntu_controller.pp
etc/t6/selinux_template/centos.te

BVS-5261, clean up heat puppet logic, add selinux policies

---

bosi/lib/constants.py

fix version number for liberty

---

bosi/lib/constants.py

give liberty the right version

---

bosi/lib/constants.py

makes bosi work with liberty

---

etc/t6/puppet_template/centos_compute.pp
etc/t6/puppet_template/ubuntu_compute.pp

fix neutron-bsn-agent service file for liberty

---

etc/t6/puppet_template/centos_compute.pp

fix dependency for dhcp-agent

---

bosi/lib/constants.py

add --certificate to ivs

---

etc/t5/puppet_template/centos_compute.pp
etc/t5/puppet_template/centos_controller.pp

fix liberty t5 packstack

---

etc/t5/puppet_template/centos_compute.pp
etc/t5/puppet_template/ubuntu_compute.pp

force to use dhcp namespace for metadata in t5

---

bosi/bosi.py
bosi/lib/constants.py
bosi/lib/environment.py
bosi/lib/helper.py
bosi/lib/node.py
etc/bosi_config/config.yaml
etc/t5/bash_template/centos_7.sh
etc/t5/bash_template/redhat_7.sh
etc/t5/bash_template/ubuntu_14.sh
etc/t6/bash_template/centos_7.sh
etc/t6/bash_template/ubuntu_14.sh
etc/t6/python_template/dpid.py

This PR addresses issues with CPSEC(BSC-8748) and pip proxy (BVS-5492)

CPSEC and pip proxy

---

bosi/bosi.py
etc/t5/python_template/dpid.py

BVS-5412, improve log collection

---

bosi/lib/rest.py

change port-group to interface-group

---

etc/t5/puppet_template/centos_controller.pp
etc/t6/puppet_template/centos_controller.pp

BVS-5522, fix glance paste

---

etc/t5/bash_template/centos_7.sh
etc/t5/bash_template/ubuntu_14.sh
etc/t6/bash_template/centos_7.sh
etc/t6/bash_template/ubuntu_14.sh

install horizon-bsn

---

bosi/scripts/ifdown-ivs
bosi/scripts/ifup-ivs

add ifup ifdown for ivs uplinks

---

etc/t5/bash_template/centos_7.sh
etc/t5/bash_template/ubuntu_14.sh
etc/t6/bash_template/centos_7.sh
etc/t6/bash_template/ubuntu_14.sh

deploy horizon plugin

---

bosi/lib/helper.py

add missing pip_proxy

---

bosi/lib/node.py

fix pip_proxy typo

---

bosi/bosi.py
bosi/lib/helper.py

rename cert files for ivs

---

etc/t5/puppet_template/centos_controller.pp
etc/t6/puppet_template/centos_controller.pp

BVS-5585, fix paste config for heat

---

bosi/scripts/pre_request.sh

BVS-5586, improve pre_request script

---

bosi/lib/constants.py
etc/bosi_config/config.yaml

enable --certificate

---

etc/t5/puppet_template/centos_controller.pp
etc/t6/puppet_template/centos_controller.pp

add glance filesystem_store_datadir

---

bosi/bosi.py

BVS-5644 add missing import

---

etc/t6/bash_template/centos_7.sh

restart ivs at the end

---

etc/t6/puppet_template/centos_compute.pp

BVS-5653, postpone restart ivs

---

etc/t6/bash_template/centos_7.sh

BVS-5653, postpone ivs restart

---

etc/t5/bash_template/centos_7.sh
etc/t5/puppet_template/centos_controller.pp
etc/t5/puppet_template/ubuntu_controller.pp
etc/t6/bash_template/centos_7.sh
etc/t6/puppet_template/centos_controller.pp
etc/t6/puppet_template/ubuntu_controller.pp

BVS-5666, install funcsigs

---

etc/t5/puppet_template/centos_controller.pp
etc/t6/puppet_template/centos_controller.pp

BVS-5726, fix heat.conf

---

bosi/bosi.py
bosi/lib/helper.py

BVS-5705, check if tenant traffic uses vlan

---

etc/t5/bash_template/centos_7.sh
etc/t5/bash_template/redhat_7.sh
etc/t5/bash_template/ubuntu_14.sh
etc/t6/bash_template/centos_7.sh
etc/t6/bash_template/ubuntu_14.sh

- kilo works a little differently for db upgrade
- added the `if-else` to handle it
- _note_: `kilo_v2` only. not `kilo`

BVS-5759 add special case db upgrade for kilo

---

etc/t5/puppet_template/centos_controller.pp
etc/t5/puppet_template/ubuntu_controller.pp
etc/t6/puppet_template/centos_controller.pp
etc/t6/puppet_template/ubuntu_controller.pp

BVS-5477, include port-security extension

---

bosi/lib/helper.py

fix vlan check

---

etc/t5/puppet_template/centos_controller.pp
etc/t5/puppet_template/ubuntu_controller.pp
etc/t6/puppet_template/centos_controller.pp
etc/t6/puppet_template/ubuntu_controller.pp

remove port_security from bosi

---

etc/t6/puppet_template/centos_controller.pp

fix neutron-openvswitch-agent path

---

bosi/lib/helper.py

BVS-5837, collect nova and heat logs

---

setup.cfg

BVS-5863 update bosi to new release

---

etc/t5/bash_template/centos_7.sh
etc/t5/bash_template/redhat_7.sh
etc/t5/bash_template/ubuntu_14.sh
etc/t6/bash_template/centos_7.sh
etc/t6/bash_template/ubuntu_14.sh
setup.cfg

change kilo version string to check both kilo and kilo_v2

---

bosi/lib/helper.py

program membership rules during installation

---

setup.cfg

update version to 2.0.21

---

bosi/lib/constants.py
bosi/lib/helper.py
etc/t5/bash_template/ubuntu_14.sh
etc/t5/puppet_template/ubuntu_cinder.pp
etc/t6/bash_template/ubuntu_14.sh
etc/t6/puppet_template/ubuntu_cinder.pp

BVS-5872 run lldp on cinder node

---

etc/bosi_config/config.yaml
setup.cfg

set default to kilo

---

bosi/lib/constants.py
bosi/lib/helper.py

BSC-9146, use correct CN

---

bosi/scripts/ifup-ivs

BVS-6124, start ivs before adding port to ivs

---

bosi/scripts/assign-ivs-ip.sh
bosi/scripts/ifup-ivs

BVS-6124, assign ip address to ivs internal ports

---

bosi/bosi.py
bosi/lib/constants.py
bosi/lib/environment.py
bosi/lib/helper.py
bosi/lib/node.py
bosi/scripts/pre_request.sh
etc/t5/ospurge_template/purge_all.sh
etc/t6/bash_template/redhat_7_upgrade.sh
etc/t6/bash_template/ubuntu_14_upgrade.sh
etc/t6/ospurge_template/purge_all.sh

BVS-5892 upgrade for rhosp

---

bosi/lib/environment.py
bosi/lib/helper.py
etc/t6/bash_template/centos_7_upgrade.sh
etc/t6/bash_template/ubuntu_14_upgrade.sh

BVS-5892, trivial fix for rhosp upgrade

---

etc/t6/bash_template/redhat_7_upgrade.sh

BVS-5892, force reinstall ivs rpm in redhat

---

bosi/lib/environment.py

BVS-5892, fix TypeError

---

bosi/scripts/startup.sh

add startup script

---

bosi/lib/helper.py

cleanup dst dir before copying files to it

---

bosi/lib/helper.py

bypass error nodes in rhosp

---

bosi/lib/helper.py
bosi/scripts/startup.sh
etc/t6/bash_template/centos_7.sh
etc/t6/bash_template/ubuntu_14.sh

BVS-6268, fix startup script

---

etc/t5/bash_template/centos_7_upgrade.sh
etc/t5/bash_template/redhat_7_upgrade.sh
etc/t5/bash_template/ubuntu_14_upgrade.sh
etc/t6/bash_template/ubuntu_14.sh

BVS-6268, use rpm instead of yum to install rpm

---

etc/t5/bash_template/redhat_7_upgrade.sh
etc/t6/bash_template/redhat_7_upgrade.sh

BVS-6302, systemctl daemon-reload before restart service

---

bosi/lib/rest.py

BVS-6306, dynamically use port-group or interface-group

---

etc/t6/bash_template/ubuntu_14.sh
etc/t6/puppet_template/ubuntu_compute.pp

fix kilo deployment with fuel

---

bosi/lib/constants.py
bosi/lib/helper.py
etc/t6/bash_template/ubuntu_14.sh

BVS-6324, make bosi compatible with kilo

---

bosi/lib/constants.py

fix certificate directory

---

.gitignore
build/upload_to_pypi.sh

add script to upload to pypi

---

setup.cfg

bump version to check upload

---

build/upload_to_pypi.sh
docker/ubuntu/Dockerfile

update build process

---

build/upload_to_pypi.sh

change mount point and git config update

---

build/upload_to_pypi.sh

handle special permission magic stuff

---

docker/ubuntu/Dockerfile

organize dockerfile

---

build/upload_to_pypi.sh
docker/ubuntu/Dockerfile

cherry pick build changes from master

---

bosi/scripts/README
bosi/scripts/startup.sh

update bosi for rhosp packaging automated job

---

bosi/bosi.py
bosi/lib/constants.py
bosi/lib/environment.py
bosi/lib/node.py
etc/bosi_config/config.yaml
setup.cfg

Reviewer: @wolverineav 
bsnstacklib has new version scheme: os_release.bcf_release.bug_fix

use new version scheme for bsnstacklib

---

bosi/scripts/customize.sh

prepare virt-edit scripts

---

etc/t6/bash_template/ubuntu_14.sh
setup.cfg

BVS-6324, add --force-yes for libnl

---

etc/t6/bash_template/ubuntu_14.sh

trigger a build

---

etc/t6/bash_template/ubuntu_14.sh
setup.cfg

BVS-6324, add force yes for kilo p+v

---

bosi/lib/constants.py
setup.cfg

BVS-6545 remove verbose option from ivs daemon args [cherry-pick]

---

etc/t5/bash_template/centos_7.sh
etc/t6/bash_template/centos_7.sh
setup.cfg

BVS-6559: remove yum update from bosi

---

etc/t5/bash_template/centos_7.sh
etc/t6/bash_template/centos_7.sh
setup.cfg

BVS-6559: remove yum update from bosi [cherry-pick]

---

etc/t6/bash_template/centos_7.sh
setup.cfg

BVS-6559 removed yum update, so remove specific package install too

---

etc/t6/bash_template/centos_7.sh
setup.cfg

BVS-6559 removed yum update, so remove specific package install too [cherry-pick]

---

bosi/scripts/startup.sh
setup.cfg

remove ivs from p-only deployments

---

bosi/bosi.py
bosi/lib/constants.py
bosi/lib/environment.py
etc/bosi_config/config.yaml
etc/t6/puppet_template/ubuntu_compute.pp
etc/t6/puppet_template/ubuntu_controller.pp

add version for mitaka

---

bosi/bosi.py
bosi/lib/helper.py

Don't copy config to compute nodes with fuel p+v

---

bosi/lib/constants.py
etc/t6/puppet_template/centos_controller.pp
setup.cfg

add bcf4.0 and bump test version to 0.0.174

---

bosi/lib/constants.py
bosi/lib/helper.py
etc/t5/bash_template/centos_7.sh
etc/t5/bash_template/ubuntu_14.sh
etc/t5/puppet_template/ubuntu_controller.pp
etc/t6/bash_template/centos_7.sh
etc/t6/bash_template/ubuntu_14.sh
etc/t6/puppet_template/centos_compute.pp
etc/t6/puppet_template/centos_controller.pp
etc/t6/puppet_template/ubuntu_controller.pp
setup.cfg

make bosi work with packstack mitaka

---

bosi/lib/constants.py
bosi/lib/environment.py
setup.cfg

fix typo for mitaka

---

etc/t5/bash_template/ubuntu_14.sh
etc/t6/bash_template/ubuntu_14.sh
setup.cfg

fix kilo neutron db

---

bosi/lib/constants.py
bosi/lib/environment.py
etc/t5/bash_template/ubuntu_14.sh
etc/t6/bash_template/ubuntu_14.sh
setup.cfg

cherry pick from master

---

setup.cfg

bump version for fuel liberty

---

setup.cfg

bump test version for packstack mitaka

---

setup.cfg

release bosi for 3.7

---

bosi/lib/constants.py
bosi/lib/environment.py
setup.cfg

- thanks for the catch and suggesting fix here instead of stacklib version bump :)
- this was easier than i thought. thanks to @xinwu for that.

BVS-6867: fix bosi to pick right version of bsnstacklib

---

bosi/lib/constants.py
bosi/lib/environment.py
setup.cfg

BVS-6867: fix bosi to pick right version of bsnstacklib [cherry-pick]

---

bosi/rhosp_resources/yamls/yaml_syntax_check.py

BVS-6803: add yaml syntax checker script

---

bosi/rhosp_resources/build_scripts/rhosp_nfvswitch_packager.sh
bosi/rhosp_resources/build_scripts/rhosp_packager.sh

BVS-7020: move rhosp build scripts to bosi

---

bosi/rhosp_resources/build_scripts/rhosp_nfvswitch_packager.sh
bosi/rhosp_resources/build_scripts/rhosp_packager.sh

BVS-7020: move rhosp build scripts to bosi [cherry-pick]

---

bosi/rhosp_resources/build_scripts/rhosp_nfvswitch_packager.sh
bosi/rhosp_resources/build_scripts/rhosp_packager.sh
build/upload_to_pypi.sh

BVS-7020: address comments + ivs branch pick logic

---

bosi/lib/constants.py
bosi/lib/environment.py
bosi/rhosp_resources/build_scripts/rhosp_nfvswitch_packager.sh
bosi/rhosp_resources/build_scripts/rhosp_packager.sh
build/upload_to_pypi.sh
setup.cfg

- just getting the build changes to 3.7 along with the compatibility matrix

merge recent master changes into 3.7 [cherry-pick]

---

bosi/lib/constants.py
bosi/lib/environment.py
bosi/rhosp_resources/build_scripts/rhosp_packager.sh
build/upload_to_pypi.sh

- cherry picking build changes

merge recent master changes into 3.6 [cherry-pick]

---

setup.cfg

CC: @wolverineav 
Any side-effects you see due to previous bump?

undo version unintentional bump

---

bosi/rhosp_resources/build_scripts/rhosp_nfvswitch_packager.sh
bosi/rhosp_resources/build_scripts/rhosp_packager.sh
build/upload_to_pypi.sh

- missed this cherrypick causing build failure

BVS-7020: address comments + ivs branch pick logic [cherry-pick]

---

bosi/rhosp_resources/nfvswitch/customize.sh
bosi/rhosp_resources/nfvswitch/startup.sh

BVS-6664: nfvswitch: patch qemu rpms and update grub for compute nodes

---

bosi/rhosp_resources/build_scripts/rhosp_packager.sh

beta1 changes

---

bosi/rhosp_resources/nfvswitch/startup.sh

Cherrypick 7bdfbbb0b023d85a840fe18cbfd734b8d4a9793a

BVS-6664: update kernel boot params only on compute nodes

---

bosi/rhosp_resources/nfvswitch/osnet-patch/impl_ifcfg.py
bosi/rhosp_resources/nfvswitch/osnet-patch/objects.py

nfvswitch: include latest os-net-config changes

---

bosi/bosi.py
etc/bosi_config/config.yaml
setup.cfg

- acking the trivial change to get it tested soon.

BVS-6814: add back redhat option to bosi

---

bosi/rhosp_resources/build_scripts/rhosp_nfvswitch_packager.sh
bosi/rhosp_resources/nfvswitch/customize.sh
bosi/rhosp_resources/nfvswitch/startup.sh
bosi/rhosp_resources/yamls/bigswitch-config-nfv.yaml
bosi/rhosp_resources/yamls/compute-nfv.yaml

nfvswitch: update packager and and yaml files

---

bosi/rhosp_resources/build_scripts/rhosp_nfvswitch_packager.sh
bosi/rhosp_resources/build_scripts/rhosp_packager.sh

build_script: correctly check for unbound variables

---

bosi/rhosp_resources/build_scripts/rhosp_nfvswitch_packager.sh
bosi/rhosp_resources/build_scripts/rhosp_packager.sh

build_script: fix type

---

bosi/rhosp_resources/nfvswitch/customize.sh
bosi/rhosp_resources/nfvswitch/selinux-config

nfvswitch: patch selinux to permissive mode

---

bosi/bosi.py
etc/bosi_config/config.yaml

Reviewer: @wolverineav
- but only support upgrading

BVS-6814: add back redhat option to bosi [cherry-pick]

---

bosi/rhosp_resources/build_scripts/rhosp_nfvswitch_packager.sh

nfvswitch build_script: update version of nfvswitch like IVS

---

bosi/rhosp_resources/build_scripts/rhosp_nfvswitch_packager.sh
bosi/rhosp_resources/build_scripts/rhosp_packager.sh
bosi/rhosp_resources/ivs/README
bosi/rhosp_resources/ivs/customize.sh
bosi/rhosp_resources/ivs/startup.sh
bosi/rhosp_resources/nfvswitch/customize.sh
bosi/rhosp_resources/nfvswitch/startup.sh

Reviewer: @sarath-kumar
- not adding the revision param as discussed, since revision is static for all packages except ivs
- and for ivs, it is part of the version string for `beta`

IVS revision is special cased for beta

---

bosi/rhosp_resources/build_scripts/rhosp_nfvswitch_packager.sh
bosi/rhosp_resources/build_scripts/rhosp_packager.sh
bosi/rhosp_resources/ivs/README
bosi/rhosp_resources/ivs/customize.sh
bosi/rhosp_resources/ivs/startup.sh
bosi/rhosp_resources/nfvswitch/README
bosi/rhosp_resources/nfvswitch/customize.sh
bosi/rhosp_resources/nfvswitch/startup.sh

IVS revision is special cased for beta [cherry-pick]

---

bosi/rhosp_resources/build_scripts/rhosp_packager.sh

Reviewer: @wolverineav
- cherry-pick

update script for liberty_ksv3 branch [cherry-pick]

---

bosi/rhosp_resources/build_scripts/rhosp_nfvswitch_packager.sh
bosi/rhosp_resources/build_scripts/rhosp_packager.sh

- `RHOSP` version for newton is `10`, right?

add new openstack-RHOSP mapping for newton

---

bosi/rhosp_resources/build_scripts/rhosp_nfvswitch_packager.sh
bosi/rhosp_resources/build_scripts/rhosp_packager.sh

add new openstack-RHOSP mapping for newton [cherry-pick]

---

bosi/rhosp_resources/build_scripts/rhosp_packager.sh

- in case more such branches pop-up, i'll ask kiran to come up with a pattern so that we don't keep adding special cases

handle special case for 3.6.2-A branch

---

bosi/rhosp_resources/build_scripts/rhosp_packager.sh

for any liberty branch, use stable/liberty in horizon-bsn plugin [cherry-pick]

---

bosi/rhosp_resources/ivs/customize.sh

customize: remove ivs ifcfg scripts

---

bosi/lib/helper.py

- after `nova list`, it will perform one more check using `ironic node-show` to get `profile` of the node - which is either control, compute, ceph or something else
- right now, it'll work for control, compute and ceph. for future roles that might be added, we'll have to keep a watch and modify if necessary

OSP-10: identify node role correctly in rhosp env

---

bosi/lib/helper.py

OSP-10: identify node role correctly in rhosp env [cherry-pick]

---

build/upload_to_pypi.sh
requirements.txt

OSP-8 offline installation

---

build/upload_to_pypi.sh

update download command

---

build/upload_to_pypi.sh
requirements.txt

OSP-8 offline installation [cherry-pick]

---

bosi/rhosp_resources/build_scripts/rhosp_nfvswitch_packager.sh
bosi/rhosp_resources/build_scripts/rhosp_packager.sh

include offline installation package in tarball

---

bosi/rhosp_resources/build_scripts/rhosp_nfvswitch_packager.sh
bosi/rhosp_resources/build_scripts/rhosp_packager.sh

include offline installation package in tarball [cherry-pick]

---

bosi/rhosp_resources/build_scripts/rhosp_nfvswitch_packager.sh

update bosi to pick nfvswitch package after update [cherry-pick]

---

bosi/lib/constants.py
setup.cfg

add 4.1.0 verion info to bosi constants [cherry-pick]

---

etc/t5/bash_template/redhat_7_upgrade.sh
etc/t6/bash_template/centos_7.sh
etc/t6/bash_template/centos_7_upgrade.sh
etc/t6/bash_template/redhat_7_upgrade.sh
setup.cfg

OSP-32: cleanup old versions when upgrading packages [cherry-pick]

---

bosi/rhosp_resources/yamls/bigswitch-config-pv.yaml

OSP-53: disable l3 agent in P+V

---

bosi/bosi.py
bosi/lib/environment.py
bosi/lib/helper.py
bosi/lib/node.py
etc/t5/bash_template/centos_7.sh
etc/t5/bash_template/ubuntu_14.sh
etc/t6/bash_template/centos_7.sh
etc/t6/bash_template/ubuntu_14.sh
setup.cfg

Reviewer: @wolverineav
- release for testing

BVS-7989: add option for offline installation

---

bosi/rhosp_resources/build_scripts/rhosp_nfvswitch_packager.sh
bosi/rhosp_resources/build_scripts/rhosp_packager.sh

- building multiple tars on same day causes overlap :|

include time in tarname as well

---

bosi/rhosp_resources/build_scripts/rhosp_nfvswitch_packager.sh
bosi/rhosp_resources/build_scripts/rhosp_packager.sh

- building multiple tars on same day causes overlap :|

include time in tarname as well [cherry-pick]

---

bosi/bosi.py
bosi/lib/environment.py
bosi/lib/helper.py
bosi/lib/node.py
etc/t5/bash_template/centos_7.sh
etc/t5/bash_template/ubuntu_14.sh
etc/t6/bash_template/centos_7.sh
etc/t6/bash_template/ubuntu_14.sh
setup.cfg

- do not merge until 4.0 version is released first

BVS-7989: add option for offline installation [cherry-pick]

---

bosi/lib/helper.py
setup.cfg

missed this earlier during the merge.

dangling change for bsnstacklib to networking-bigswitch

---

etc/t5/bash_template/centos_7.sh
etc/t5/bash_template/ubuntu_14.sh
etc/t6/bash_template/centos_7.sh
etc/t6/bash_template/ubuntu_14.sh
setup.cfg

-  and make dependency installation optional

correct the path for install_pkg

---

etc/t5/bash_template/centos_7.sh
etc/t5/bash_template/ubuntu_14.sh
etc/t6/bash_template/centos_7.sh
etc/t6/bash_template/ubuntu_14.sh
setup.cfg

-  and make dependency installation optional
Conflicts:
etc/t5/bash_template/centos_7.sh
etc/t5/bash_template/ubuntu_14.sh
etc/t6/bash_template/centos_7.sh
etc/t6/bash_template/ubuntu_14.sh

correct the path for install_pkg [cherry-pick to 4.0.0]

---

bosi/bosi.py
bosi/lib/constants.py
bosi/lib/helper.py
bosi/lib/node.py
etc/bosi_config/config.yaml
etc/t6/bash_template/redhat_7_sriov.sh
setup.cfg

- system-desc is set to a default as `--system-desc 5c:16:c7:00:00:00` - as previously tested by Prashanth.

OSP-55: bosi changes to support SR-IOV compute node configuration

---

bosi/lib/constants.py
bosi/lib/environment.py
bosi/lib/helper.py
bosi/lib/node.py
etc/bosi_config/config.yaml
etc/t6/bash_template/redhat_7_sriov.sh
setup.cfg

OSP-64: support active-active mode only

---

bosi/bosi.py
bosi/lib/constants.py
bosi/lib/environment.py
bosi/lib/helper.py
bosi/lib/node.py
etc/bosi_config/config.yaml
etc/t6/bash_template/redhat_7_sriov.sh
setup.cfg

- includes all changes from master combined

OSP-55: bosi changes to support SR-IOV compute node configuration [cherry-pick]

---

bosi/lib/environment.py
setup.cfg

- wait until release
Reverts bigswitch/bosi#405

Revert "OSP-66: ignore mission sriov option [cherry-pick]"

---

bosi/rhosp_resources/master/yamls/controller-multiple-ovs.yaml
bosi/rhosp_resources/master/yamls/controller-single-ovs.yaml

update controller yaml files for newton and upwards

---

bosi/rhosp_resources/master/yamls/bigswitch-config-p.yaml
bosi/rhosp_resources/master/yamls/bigswitch-config-pv.yaml
bosi/rhosp_resources/master/yamls/ceph-storage.yaml
bosi/rhosp_resources/master/yamls/compute-ivs-ovs.yaml
bosi/rhosp_resources/master/yamls/compute-nfv.yaml
bosi/rhosp_resources/master/yamls/controller-multiple-ovs.yaml
bosi/rhosp_resources/master/yamls/neutron-bigswitch-agent.yaml
bosi/rhosp_resources/master/yamls/neutron-ml2-bigswitch.yaml_compute
bosi/rhosp_resources/master/yamls/neutron-ml2-bigswitch.yaml_controller
bosi/rhosp_resources/master/yamls/node-info.yaml

update yaml files based on May 1 status

---

bosi/rhosp_resources/master/nfvswitch/startup.sh

update nfv startup.sh to match ivs startup.sh

---

bosi/rhosp_resources/master/yamls/first-boot-nfv.yaml
bosi/rhosp_resources/master/yamls/first-boot-sriov.yaml

Add a sleep in firstboot before rebooting

---

bosi/rhosp_resources/master/yamls/first-boot-nfv.yaml
bosi/rhosp_resources/master/yamls/first-boot-sriov.yaml

CC: @wolverineav 
git cherry-pick 30178e08e4d4b29f042e9aa870439bd3f299a385

Add a sleep in firstboot before rebooting 

---

etc/t6/bash_template/redhat_7_sriov.sh
setup.cfg

- corresponding deployment change to https://review.openstack.org/#/c/466124/

OSP-64: add --sriov flag as param to send_lldp

---

bosi/bosi.py
bosi/lib/constants.py
bosi/lib/environment.py
bosi/lib/helper.py
bosi/lib/node.py
build/upload_to_pypi.sh
etc/bosi_config/config.yaml
etc/t6/bash_template/redhat_7_sriov.sh
etc/t6/bash_template/redhat_7_upgrade.sh
setup.cfg

CC: @padubidry @songbeng 
- @padubidry i believe we have tested the latest bosi 0.0.204 for deployment with and without sriov.
- @songbeng mentioned beta testing 4.2 in a customer setup requires actual release of bosi, so cherry-picking the pending changes.

cherry-pick all changes for sriov from master to bcf-4.0.0

---

bosi/rhosp_resources/origin/stable/mitaka/build_scripts/rhosp_nfvswitch_packager.sh

update nfvswitch build script to define HorizonBsnBranch var

---

bosi/rhosp_resources/origin/stable/mitaka/build_scripts/rhosp_nfvswitch_packager.sh

update nfvswitch build script to define HorizonBsnBranch var [cherry-pick]

---

build/upload_to_pypi.sh

- pypi inside the container is using cache probably and not
fetching the latest one :|

update build script to stop checking version

---

bosi/rhosp_resources/master/ivs/startup.sh
bosi/rhosp_resources/master/nfvswitch/startup.sh
bosi/rhosp_resources/origin/stable/mitaka/ivs/startup.sh
bosi/rhosp_resources/origin/stable/mitaka/nfvswitch/startup.sh

- missed a script path earlier

OSP-32: ensure package cleanup in fresh install case as well

---

bosi/rhosp_resources/master/ivs/startup.sh
bosi/rhosp_resources/master/nfvswitch/startup.sh
bosi/rhosp_resources/origin/stable/mitaka/ivs/startup.sh
bosi/rhosp_resources/origin/stable/mitaka/nfvswitch/startup.sh
setup.cfg

OSP-32: ensure package cleanup in fresh install case as well [cherry-pick]

---

bosi/lib/environment.py
bosi/lib/helper.py
bosi/lib/node.py
bosi/rhosp_resources/master/yamls/network-environment-ivs.yaml
bosi/rhosp_resources/master/yamls/network-environment-nfv.yaml
docker/ubuntu/Dockerfile
setup.cfg

OSP-129: remove unused method to get IP of setup node

---

bosi/rhosp_resources/master/yamls/network-environment-ivs.yaml
bosi/rhosp_resources/master/yamls/network-environment-nfv.yaml
docker/ubuntu/Dockerfile

- add packages to container as required

OSP-133: update net-env.yaml for RHEL7.4 changes [cherry-pick]

---

bosi/lib/helper.py

don't crap out at parsing error, continue [cherry-pick]

---

bosi/rhosp_resources/master/yamls/compute-single-ivs.yaml
bosi/rhosp_resources/master/yamls/compute-single-ovs.yaml
bosi/rhosp_resources/master/yamls/controller-multiple-ovs.yaml
bosi/rhosp_resources/master/yamls/controller-single-ovs.yaml

- applying same hierarchy change as done for `compute-ivs-ovs.yaml` in previous PR

fix yaml files other than the one used

---

bosi/rhosp_resources/master/yamls/yaml_validate.py
setup.cfg

OSP-139: simplify help text and improve error handling

---

bosi/rhosp_resources/master/yamls/yaml_validate.py
setup.cfg

OSP-139: simplify help text and improve error handling [cherry-pick]

---

bosi/rhosp_resources/master/build_scripts/rhosp_packager.sh

complete package pull during RHOSP tarball build

---

build/upload_to_pypi.sh

- changed it for other projects, but missed in core bosi itself :|

build script change for bosi

---

etc/t5/puppet_template/centos_compute.pp
setup.cfg

BCF-10034: udpate list parsing in puppet [cherry-pick]

---

etc/bosi_config/config.yaml
setup.cfg

BFC-10008: update openstack_release documentation [cherry-pick]

---

etc/t5/bash_template/redhat_7_upgrade.sh
etc/t6/bash_template/redhat_7_upgrade.sh
setup.cfg

- trivial change, major service impact when it breaks :|

don't remove packages while upgrading

---

etc/t5/bash_template/redhat_7_upgrade.sh
etc/t6/bash_template/redhat_7_upgrade.sh
setup.cfg

- cherry-pick for the master change

don't remove packages while upgrading [cherry-pick]

---

bosi/rhosp_resources/master/yamls/bigswitch_container_images.yaml

CC: @WeifanFu-bsn 
- this file is mentioned in the deployment guide, but is missing
in the bundle.

add missing yaml file for pike release

---

bosi/rhosp_resources/master/yamls/bigswitch_container_images.yaml

add missing yaml file for pike release [cherry-pick]

---

etc/t5/bash_template/redhat_7_upgrade.sh
etc/t6/bash_template/redhat_7_upgrade.sh
setup.cfg

revert rum remove change

---

etc/t5/bash_template/redhat_7_upgrade.sh
etc/t6/bash_template/redhat_7_upgrade.sh
setup.cfg

Revert "don't remove packages while upgrading"

---

setup.cfg

bump version to push yaml changes on bigtop

---

bosi/rhosp_resources/master/ivs/README
bosi/rhosp_resources/master/ivs/customize.sh
bosi/rhosp_resources/master/ivs/startup.sh

update customize scripts to include only neutron-bsn-lldp [cherry-pick]

---

bosi/rhosp_resources/master/yamls/local_registry_images_bigswitch.yaml
bosi/rhosp_resources/master/yamls/overcloud_images_bigswitch.yaml

include horizon container images as well [cherry-pick]

---

bosi/rhosp_resources/master/yamls/local_registry_images_bigswitch.yaml
bosi/rhosp_resources/master/yamls/overcloud_images_bigswitch.yaml

- trailing change to complete the P-only story

include horizon container images as well

---

bosi/rhosp_resources/master/yamls/bigswitch-config-pv.yaml
bosi/rhosp_resources/master/yamls/local_registry_images_bigswitch.yaml
bosi/rhosp_resources/master/yamls/neutron-bigswitch-agent.yaml
bosi/rhosp_resources/master/yamls/overcloud_images_bigswitch.yaml

- i was keep this separate to test later
- turns out P+V is first to be tested, so merging it now :)

add P+V changes for RHOSP 13

---

bosi/rhosp_resources/master/yamls/bigswitch-config-pv.yaml
bosi/rhosp_resources/master/yamls/local_registry_images_bigswitch.yaml
bosi/rhosp_resources/master/yamls/neutron-bigswitch-agent.yaml
bosi/rhosp_resources/master/yamls/overcloud_images_bigswitch.yaml

add P+V changes for RHOSP 13 [cherry-pick]

---

bosi/rhosp_resources/master/yamls/compute.yaml_ivs
bosi/rhosp_resources/master/yamls/compute.yaml_ovs
bosi/rhosp_resources/master/yamls/controller.yaml
bosi/rhosp_resources/master/yamls/overcloud_images_bigswitch.yaml

CC: @padubidry 
- there are minor nuances which may affect deployment
- updated to match to a T

match network config yaml files to queens version of heat templates

---

bosi/rhosp_resources/master/yamls/compute.yaml_ivs
bosi/rhosp_resources/master/yamls/compute.yaml_ovs
bosi/rhosp_resources/master/yamls/controller.yaml
bosi/rhosp_resources/master/yamls/overcloud_images_bigswitch.yaml

- there are minor nuances which may affect deployment
- updated to match to a T

match network config yaml files to queens version of heat templates [cherry-pick]

---

bosi/rhosp_resources/master/yamls/local_registry_images_bigswitch.yaml
bosi/rhosp_resources/master/yamls/overcloud_images_bigswitch.yaml

OSP-227: update image tag to pick latest stable container image [cherry-pick]

---

bosi/rhosp_resources/master/ivs/impl_ifcfg.py
bosi/rhosp_resources/master/yamls/local_registry_images_bigswitch.yaml
bosi/rhosp_resources/master/yamls/overcloud_images_bigswitch.yaml

- trivial changes to bump version

OSP-227: update image tag to pick latest stable container image

---

bosi/rhosp_resources/master/yamls/local_registry_images_bigswitch.yaml
bosi/rhosp_resources/master/yamls/overcloud_images_bigswitch.yaml
etc/t5/bash_template/redhat_7_upgrade.sh
etc/t6/bash_template/redhat_7_upgrade.sh
setup.cfg

- updates the redhat_upgrade script to install neutron-bsn-lldp when available
- also updates the container tag in yaml files to the latest push to connect.redhat.com

OSP-228: update BOSI to handle package updates in RHOSP 13

---

bosi/rhosp_resources/master/yamls/local_registry_images_bigswitch.yaml
bosi/rhosp_resources/master/yamls/overcloud_images_bigswitch.yaml
etc/t5/bash_template/redhat_7_upgrade.sh
etc/t6/bash_template/redhat_7_upgrade.sh
setup.cfg

OSP-228: update BOSI to handle package updates in RHOSP 13 [cherry-pick]

---

bosi/rhosp_resources/master/ivs/customize.sh
bosi/rhosp_resources/master/yamls/bigswitch-config-pv.yaml
bosi/rhosp_resources/origin/stable/newton/ivs/customize.sh
bosi/rhosp_resources/origin/stable/newton/yamls/bigswitch-config-pv.yaml
bosi/rhosp_resources/origin/stable/ocata/ivs/customize.sh
bosi/rhosp_resources/origin/stable/ocata/yamls/bigswitch-config-pv.yaml
bosi/rhosp_resources/origin/stable/pike/ivs/customize.sh
bosi/rhosp_resources/origin/stable/pike/yamls/bigswitch-config-pv.yaml

yaml and customize script changes for clarity [cherry-pick]

---

bosi/lib/helper.py
setup.cfg

- trivial change of command - backward incompatible though
- hence the new branch formation

OSP-248: update node show command

---

bosi/lib/helper.py
setup.cfg

- added this to the main PR on master branch as well

node show using instance id not uuid

---

etc/bosi_config/config.yaml

set default OSP and BCF releases to new versions

---

bosi/rhosp_resources/master/yamls/network-environment-bcf.yaml

Reviewer: @sarath-kumar @WeifanFu-bsn

add miimon=100 as a default option for ovs options [cherry-pick][4.7.0]

---

bosi/rhosp_resources/master/yamls/local_registry_images_bigswitch.yaml
bosi/rhosp_resources/master/yamls/overcloud_images_bigswitch.yaml

Reviewer: @sarath-kumar @WeifanFu-bsn

update container tag to include various unicode char fixes

---

bosi/rhosp_resources/master/yamls/bigswitch-config-pv.yaml
bosi/rhosp_resources/master/yamls/local_registry_images_bigswitch.yaml
bosi/rhosp_resources/master/yamls/neutron-bigswitch-agent.yaml
bosi/rhosp_resources/master/yamls/overcloud_images_bigswitch.yaml
bosi/rhosp_resources/origin/stable/newton/ivs/customize.sh
bosi/rhosp_resources/origin/stable/newton/ivs/startup.sh
bosi/rhosp_resources/origin/stable/newton/yamls/bigswitch-config-pv-sriov.yaml
bosi/rhosp_resources/origin/stable/newton/yamls/bigswitch-config-pv.yaml
bosi/rhosp_resources/origin/stable/ocata/ivs/customize.sh
bosi/rhosp_resources/origin/stable/ocata/ivs/startup.sh
bosi/rhosp_resources/origin/stable/ocata/yamls/bigswitch-config-pv.yaml
bosi/rhosp_resources/origin/stable/pike/ivs/customize.sh
bosi/rhosp_resources/origin/stable/pike/ivs/startup.sh
bosi/rhosp_resources/origin/stable/pike/yamls/bigswitch-config-pv.yaml

- updated `firewall_driver` to `iptables_hybrid`
- `neutron-bsn-agent` to include `ml2_conf.ini` in command args
- updated container tag to the latest one with the fix

OSP-217: changes for iptables fix

---

bosi/rhosp_resources/master/yamls/bigswitch-config-pv.yaml
bosi/rhosp_resources/master/yamls/local_registry_images_bigswitch.yaml
bosi/rhosp_resources/master/yamls/neutron-bigswitch-agent.yaml
bosi/rhosp_resources/master/yamls/overcloud_images_bigswitch.yaml
bosi/rhosp_resources/origin/stable/newton/ivs/customize.sh
bosi/rhosp_resources/origin/stable/newton/ivs/startup.sh
bosi/rhosp_resources/origin/stable/newton/yamls/bigswitch-config-pv-sriov.yaml
bosi/rhosp_resources/origin/stable/newton/yamls/bigswitch-config-pv.yaml
bosi/rhosp_resources/origin/stable/ocata/ivs/customize.sh
bosi/rhosp_resources/origin/stable/ocata/ivs/startup.sh
bosi/rhosp_resources/origin/stable/ocata/yamls/bigswitch-config-pv.yaml
bosi/rhosp_resources/origin/stable/pike/ivs/customize.sh
bosi/rhosp_resources/origin/stable/pike/ivs/startup.sh
bosi/rhosp_resources/origin/stable/pike/yamls/bigswitch-config-pv.yaml
setup.cfg

OSP-217: changes for iptables fix [cherry-pick]

---

bosi/rhosp_resources/master/ivs/clear_bcf_ssl_certs.sh
bosi/rhosp_resources/origin/stable/pike/ivs/clear_bcf_ssl_certs.sh

add helper script to clear bcf ssl certs when forced to do so [cherry-pick]

---

bosi/rhosp_resources/master/ivs/clear_bcf_ssl_certs.sh
bosi/rhosp_resources/origin/stable/pike/ivs/clear_bcf_ssl_certs.sh

Reviewer: @wolverineav 
- restart doesn't work most of the time

stop, sleep, start neutron_api container [cherry-pick]

---

bosi/rhosp_resources/master/ivs/clear_bcf_ssl_certs.sh
bosi/rhosp_resources/origin/stable/pike/ivs/clear_bcf_ssl_certs.sh

CC: @padubidry 
- restart doesn't work most of the time

stop, sleep, start neutron_api container

---

setup.cfg

bump bosi version

---

bosi/rhosp_resources/origin/stable/train/ccf-registry.txt

Update the workflow
we support only 16.1 and the integration requires using prefix and suffix for filtering

OSP-301 update integration info
