bigswitch/bosi

- etc/t6/puppet_template/centos_compute.pp
- etc/t6/puppet_template/ubuntu_compute.pp
Reviewer: @kjiang 
This field is new in liberty. We need to add it to fuel plugin for t6
> force dhcp server to append static route for metadata

- etc/t5/bash_template/centos_7.sh
- etc/t5/bash_template/redhat_7.sh
- etc/t5/bash_template/ubuntu_14.sh
- etc/t5/puppet_template/centos_controller.pp
- etc/t5/puppet_template/redhat_controller.pp
- etc/t5/puppet_template/ubuntu_controller.pp
- etc/t6/bash_template/centos_7.sh
- etc/t6/bash_template/ubuntu_14.sh
- etc/t6/puppet_template/centos_controller.pp
- etc/t6/puppet_template/ubuntu_controller.pp
- updated neutron.conf to have bsn_service_plugin listed
- execute 'neutron-db-manage upgrade heads' after bsnstacklib is installed and neutron.conf is updated
- neutron-db-manage upgrade heads is idempotent. executing it multiple times is ok
> minor fix related to bsn_service_plugin

- bosi/lib/helper.py
This is due to port-group -> interface-group change, kilo and liberty support mis-match
> skip membership rule programming

- etc/t5/bash_template/centos_7.sh
- etc/t5/bash_template/ubuntu_14.sh
- etc/t6/bash_template/centos_7.sh
- etc/t6/bash_template/ubuntu_14.sh
- since the numbering convention is same as `bsnstacklib`, we re-use the same version number variables
- redhat t5 is not modified since it doesn't include the horizon-bsn plugin at all
> horizon-bsn now has tags for release version, update bosi for the same

- etc/t5/bash_template/centos_7.sh
- etc/t5/bash_template/redhat_7.sh
- etc/t6/bash_template/centos_7.sh
- upstream fedora changes epel-release number and doesn't
retain old file
- use regex to wget and install
> BVS-5926 use regex to get and install epel-release package

- bosi/lib/constants.py
- setup.cfg
CC: @brajneesh 
- i'll cherry pick this to bcf-3.6 branch of bosi too
> BVS-6545 remove verbose option from ivs daemon args

- bosi/nfvswitch/README
- bosi/nfvswitch/customize.sh
- bosi/nfvswitch/startup.sh
Reviewer: @wolverineav 
The plan is to have a separate Jenkins Job for nfvswitch BVS-6835 which fetches necessary rpms and uses this new folder to generate the tarball.
Please verify this change doesn't break/interfere with our other builds/tarballs for Bosi/Fuel/Rhel-IVS
> BVS-6648: nfvswitch: add customize and starup scripts for rhel packaging

- bosi/lib/constants.py
- bosi/lib/environment.py
- setup.cfg
- one step closer to having a single bosi branch
- the previous way of individually picking openstack and bcf version doesn't work well
- liberty support was added in 3.6, picking 3.6 from 4.0 seems weird. instead having a map this way make it clear to figure out.
acking it since trivial change and will be required before 4.0 beta
> make openstack bcf compatibility matrix cleaner

- bosi/lib/helper.py
- setup.cfg
CC: @sarath-kumar 
- with the IVS change in, the version string according to `rpm` spec is `4.0.0`
- so we need to skip the `-beta1` found in `ivs --version`
> BVS-7020: correct verify logic for ivs 4.0.0~beta1

- bosi/rhosp_resources/build_scripts/rhosp_packager.sh
- since the `magic` is only required for master, skip it for non-master branches as ivs version number is static, unlike bsnstacklib and horizon-bsn
> beta1 changes

- bosi/rhosp_resources/nfvswitch/startup.sh
> BVS-6664: update kernel boot params only on compute nodes correctly

- bosi/bosi.py
- bosi/rhosp_resources/build_scripts/rhosp_nfvswitch_packager.sh
- bosi/rhosp_resources/build_scripts/rhosp_packager.sh
- bosi/rhosp_resources/ivs/README
- bosi/rhosp_resources/ivs/customize.sh
- bosi/rhosp_resources/ivs/startup.sh
- etc/bosi_config/config.yaml
- setup.cfg
- getting latest build related changes to 3.7
- side note: i can remove `rhosp_nfvswitch_packager.sh` since we don't have nfvswitch in 3.7?
> bring 3.7 up to date with changes in master [cherry-pick]

- bosi/rhosp_resources/build_scripts/rhosp_packager.sh
- the only thing affected with the branch path is `horizon-bsn`, since it should still point to `origin/stable/liberty` even in special case
- everything else remains same
> update script for liberty_ksv3 branch

- bosi/rhosp_resources/build_scripts/rhosp_packager.sh
- since we have multiple liberty branch. making it generic
> for any liberty branch, use stable/liberty in horizon-bsn plugin

- bosi/rhosp_resources/build_scripts/rhosp_packager.sh
- this way it isn't copied when deploying for upgrades
> use directory for bosi

- bosi/rhosp_resources/build_scripts/rhosp_nfvswitch_packager.sh
- this goes in sync with https://github.com/bigswitch/nfvswitch/pull/272
- assuming `NfvSwitchBranch` is same as `IvsBranch`. if that is not the case, we need to introduce a new variable for specifying `NfvSwitchBranch`
> update bosi to pick nfvswitch package after update

- bosi/lib/constants.py
- setup.cfg
- we support liberty and mitaka in 4.1.0, so adding it to accordingly
> add 4.1.0 verion info to bosi constants

- etc/t5/bash_template/redhat_7_upgrade.sh
- etc/t6/bash_template/centos_7.sh
- etc/t6/bash_template/centos_7_upgrade.sh
- etc/t6/bash_template/redhat_7_upgrade.sh
- setup.cfg
- it was missing a `-U` option to specify upgrade. thus creating a separate package installation
> OSP-32: cleanup old versions when upgrading packages

- bosi/bosi.py
- bosi/lib/environment.py
- bosi/lib/helper.py
- bosi/lib/node.py
- etc/bosi_config/config.yaml
- etc/t6/bash_template/redhat_7_sriov.sh
- setup.cfg
- path for send_lldp varies for redhat node as compared to centos
- args to the service are escaped with forward slashes, sed to make it back to hyphens
> OSP-55: fixes for sriov changes

- etc/t6/bash_template/redhat_7_sriov.sh
- setup.cfg
- daemonizing send_lldp results in error state
- this is because service tries to check process state and
cannot since the code spawned a daemon thread and died
> OSP-55: don't daemonize in service file

- bosi/lib/helper.py
- etc/t6/bash_template/redhat_7_upgrade.sh
- setup.cfg
CC: @sarath-kumar @padubidry 
- this only applies to RHOSP for now, since NFVSWITCH is not
supported on any other platform
> upgrade nfvswitch during RHOSP upgrade

- bosi/lib/node.py
- setup.cfg
CC: @sarath-kumar 
- error message for skipping node was being overridden midway and lost  after it. fixed it.
> fix error string being overridden with None in node.py

- bosi/lib/helper.py
- bosi/lib/node.py
- etc/bosi_config/config.yaml
- etc/t6/bash_template/redhat_7_sriov.sh
- setup.cfg
CC: @padubidry 
- i had removed the part for multiple physnets since we were supporting active-active only
- but that is required for `no-bonding` mode, so adding it back
> OSP-64: add support for no-bonding along with active-active

- bosi/lib/helper.py
- setup.cfg
CC: @khayamgondal-bsn 
- one of the properties for rabbit_hosts changed in neutron.conf
for single host and multi host deployments
> OSP-46: ensure bosi compatibility with newton+

- bosi/lib/helper.py
- trivial change - log message and continue in case of parsing error
- the following would crash bosi otherwise:
```
| 964b4c95-f0b0-4f35-a60f-90ea2908c9df | overcloud-compute-130  | ACTIVE | -          | Running     | ctlplane=192.0.2.139 |
| cedf1491-97df-4b9f-8952-000ee4c9b664 | overcloud-compute-131  | ERROR  | -          | NOSTATE     |                      |
| fac895eb-fc5f-4bf9-ab87-93921b4964e0 | overcloud-compute-131  | ERROR  | -          | NOSTATE     |                      |
| 93e16b23-7550-4556-b7da-1d20c8bd1c0f | overcloud-compute-132  | ACTIVE | -          | Running     | ctlplane=192.0.2.152 |
```
the two error nodes without info in the last column.
> don't crap out at parsing error, continue

- bosi/rhosp_resources/master/build_scripts/rhosp_packager.sh
- we moved it to bosi. dangling reference.
- tiny change, self-acking.
> container customization script not present in horizon anymore

- bosi/rhosp_resources/master/build_scripts/rhosp_packager.sh
- we moved it to bosi. dangling reference.
> container customization script not present in horizon anymore [cherry-pick]

- bosi/bosi.py
- bosi/lib/constants.py
- bosi/lib/environment.py
- bosi/lib/helper.py
- bosi/lib/node.py
- etc/bosi_config/config.yaml
- etc/t5/bash_template/redhat_7_dpdk.sh
- adds an option for dpdk, similar to sriov
- specify role and physnets for dpdk nodes in `config.yaml`
- specifying physnets is mandatory right now - but if we know there is only going to be one physnet, we can probably use the default physnet specification using `network_vlan_ranges` in `config.yaml`
> OSP-184: bosi changes to deploy LLDP script for OVS DPDK

- bosi/bosi.py
- bosi/lib/constants.py
- bosi/lib/helper.py
- bosi/lib/node.py
- etc/bosi_config/config.yaml
- etc/t5/bash_template/redhat_7_dpdk.sh
follow-up change to start lldp script on compute and controller with different hostnames.
- compute node requires hostname-phyname as systemname
- controller node needs just hostname
- role is decided by taking `ovs-dpdk` from `config.yaml` and then using control/compute derived from `nova list` on undercloud
- retrieving hostname using `cat /etc/hostname` doesn't include domain name. hence the change to `hostname -f`
> OSP-184: systemname for OVS DPDK is dependent on role of node

- bosi/rhosp_resources/master/ivs/README
- bosi/rhosp_resources/master/ivs/RUNME.sh
- bosi/rhosp_resources/origin/stable/newton/ivs/README
- bosi/rhosp_resources/origin/stable/newton/ivs/RUNME.sh
- bosi/rhosp_resources/origin/stable/ocata/ivs/README
- bosi/rhosp_resources/origin/stable/ocata/ivs/RUNME.sh
- instead of creating customize.sh and startup.sh with an array
of OSP vs BCF versions, provide stubbed scripts
- include a RUNME.sh script that updates the actual scripts based
on packages in the directory
> OSP-198: build changes to update customize scripts

- bosi/rhosp_resources/master/ivs/README
- bosi/rhosp_resources/master/ivs/RUNME.sh
- bosi/rhosp_resources/origin/stable/newton/ivs/README
- bosi/rhosp_resources/origin/stable/newton/ivs/RUNME.sh
- bosi/rhosp_resources/origin/stable/ocata/ivs/README
- bosi/rhosp_resources/origin/stable/ocata/ivs/RUNME.sh
- instead of creating customize.sh and startup.sh with an array
of OSP vs BCF versions, provide stubbed scripts
- include a RUNME.sh script that updates the actual scripts based
on packages in the directory
> OSP-198: build changes to update customize scripts [cherry-pick]

- bosi/rhosp_resources/master/yamls/bigswitch-config-p.yaml
- bosi/rhosp_resources/origin/stable/newton/yamls/bigswitch-config-p.yaml
- bosi/rhosp_resources/origin/stable/ocata/yamls/bigswitch-config-p.yaml
- many properties were not required for p-only deployment
- as noted in the jira https://bigswitch.atlassian.net/browse/OSP-211
> OSP-211: cleanup bigswitch-config-p.yaml

- bosi/rhosp_resources/master/yamls/bigswitch-config-p.yaml
- bosi/rhosp_resources/origin/stable/newton/yamls/bigswitch-config-p.yaml
- bosi/rhosp_resources/origin/stable/ocata/yamls/bigswitch-config-p.yaml
Reviewer: trivial 
- many properties were not required for p-only deployment
> OSP-211: cleanup bigswitch-config-p.yaml [cherry-pick]

- bosi/rhosp_resources/master/ivs/README
- bosi/rhosp_resources/master/ivs/customize.sh
- bosi/rhosp_resources/master/ivs/startup.sh
- this is because all other packages are now delivered as a
container starting with RHOSP-13
- i would remove the ivs portion of customize.sh as well - just waiting until we port that over to IVS jenkins job correctly
> update customize scripts to include only neutron-bsn-lldp

- setup.cfg
- because there are backward incompatible changes in BOSI starting
with queens, we create a new branch for all BOSI changes
henceforth for queens and onwards
> set version for new bcf-4.7.0 branch

- bosi/rhosp_resources/master/yamls/network-environment-bcf.yaml
Reviewer: @wolverineav @sarath-kumar 
Cherry-Pick: https://github.com/bigswitch/bosi/pull/518
- Rename network-environment-ivs.yaml to network-environment-bcf.yaml
- Change lacp=1 to lacp=fast
Based on Prashanth's feedback, the sample network-environment.yaml we provided can be used by both ovs and ivs, so renaming it to make it clear that it works with bcf.
lacp_rate change was another ask.
> [Cherry-Pick][4.7.0]Rename network-environment-ivs.yaml to network-environment-bcf.yaml nd change lacp=1 to lacp=fast

- bosi/rhosp_resources/master/yamls/network-environment-bcf.yaml
Reviewer: @wolverineav @sarath-kumar 
Cherry-Pick: https://github.com/bigswitch/bosi/pull/518
- Rename network-environment-ivs.yaml to network-environment-bcf.yaml
- Change lacp=1 to lacp=fast
Based on Prashanth's feedback, the sample network-environment.yaml we provided can be used by both ovs and ivs, so renaming it to make it clear that it works with bcf.
lacp_rate change was another ask.
> [Cherry-Pick][4.0.0]Rename network-environment-ivs.yaml to network-environment-bcf.yaml and change lacp=1 to lacp=fast

- bosi/rhosp_resources/master/yamls/network-environment-bcf.yaml
- required as per the discussion on the RH support case here: https://access.redhat.com/support/cases/#/case/02237548
> add miimon=100 as a default option for ovs options

- requirements.txt
- the security fix is not GA-ed yet to pypi, use beta4
> use beta version of pyyaml

- bosi/rhosp_resources/master/ivs/customize.sh
- bosi/rhosp_resources/master/ivs/startup.sh
- bosi/rhosp_resources/master/yamls/overcloud_images_bigswitch.yaml
Reviewer: @wolverineav 
- do not require user to enter '-1' at the end of version string
for IVS
- update container tag in commented part of overcloud images
> minor changes to add convenience

- bosi/rhosp_resources/master/ivs/customize.sh
- bosi/rhosp_resources/master/ivs/startup.sh
- bosi/rhosp_resources/master/yamls/overcloud_images_bigswitch.yaml
- do not require user to enter '-1' at the end of version string
for IVS
- update container tag in commented part of overcloud images
> minor changes to add convenience [cherry-pick]

- bosi/rhosp_resources/master/ivs/clear_bcf_ssl_certs.sh
- bosi/rhosp_resources/origin/stable/pike/ivs/clear_bcf_ssl_certs.sh
- this is currently being used by QA
- backup for the case when clearing certs is necessary
> add helper script to clear bcf ssl certs when forced to do so

- requirements.txt
- setup.cfg
- the beta version installation fails because newton env includes
pyyaml 3.10 as a dependency for other packages such as:
oslo.vmware, os-net-config, os-apply-config, diskimage-builder, etc
- match that to avoid conflicts
> update pyyaml to match newton env
